# Generated by Django 4.1.2 on 2022-10-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_film_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='born',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='died',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='year',
            field=models.DateField(null=True, unique_for_year=True),
        ),
    ]
