# Generated by Django 4.1.2 on 2022-10-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_director_born_director_died_film_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.DateField(null=True, verbose_name='%Y'),
        ),
    ]
